### PR TITLE
Replace SuSEFirewall by firewalld

### PR DESCRIPTION
**Pull request by teclator**
- [Trello Card](https://trello.com/c/99OkErr6/1093-8-firewall-firewalld-is-the-new-susefirewall-cwm)
- It depends on some pending modifications in yast-yast2.

### CODE REVIEW

**Comment by mvidner** [comment]
OK, maybe put in a `Requires: yast2 >= 9.9.9 # FIXME` so that we don't forget?

**Comment by teclator** [comment]
@mvidner sure, it will be needed, thnx for check the PR ;). It will not be ready until we finish the CWMFirewallInterfaces adaptation

**Comment by ls-zhu** [comment]
THANKS for this PR

**Comment by ls-zhu** [comment]
looks good to me. @mvidner

**Pull request merged**
