### PR TITLE
It is a bug fix for BNC#933564, yast did not describe initiator acls …

### PR DESCRIPTION
**Pull request by izhu**
It is a bug fix for BNC#933564, it is not a functional bug, but no one can understand when show a dialog titled with "Modify ISCSI Target Client setup". It meant to define a access control for the initiators. In iSCSI, we call the client "Initiator"

### CODE REVIEW

**Comment by kobliha** [comment]
@cwh42 @gabi2 Please review, thanks in advance

**Comment by izhu** [comment]
Ping

**Comment by cwh42** [comment]
LGTM.
Also for you, @gabi2?

**Comment by izhu** [comment]
Ping

**Comment by izhu** [comment]
Thanks, I would close it and create a feature request later

**Pull request closed without merging**
