### PR TITLE
It is a bug fix for BNC#936990

### PR DESCRIPTION
**Pull request by izhu**
It is a bug fix for Bug 936990 - [yast2-iscsi-lio-server] malfunction when uncheck "Use Authentication" for a target

### CODE REVIEW

**Comment by gabi2** [comment]
And there is also a feature request for setting up targets which allow access for any client (where demo mode is used for), see fate#318406.

**Comment by izhu** [comment]
I think this patch just fixed the problem.
The problem is: if we create a target without any authentications with Yast, When we try to access the target without any authentications, we will failed in that.
The root cause is: we need to set it to demo mode, which the patch does.

**Comment by izhu** [comment]
For bnc#919474, I think it is a different thing and different workaround, and I think there are only two options for the target: (1) a ACL including initiator name, usernames and passwords. (2)Demo mode. there is not a third way.

For fate#318406, I think it is about how ACL works, but we can find this:
There is already a mode for lio called "demo mode" that allows unrestricted access. So we should set the target to be in demo mode status if "No Authentication"

we can find this in LIO-utils manual:
Authentication should not be disabled in production setups, hence it is referred to as “demo mode”. If 
demo mode is enabled, all Initiators can access all LUNs on the specified iSCSI Endpoint.

we can find this in TargetCLI online documents:
For simple demo setups, "open" access can be granted to all initiators so that they can access all LUNs in the TPG without further authentication

Hope we can review the patch again

**Comment by gabi2** [comment]
Please see fate #316261, access to a lio target without authentication set works like expected.

**Comment by izhu** [comment]
I see the fate would support IPV6, I also see the last comment of the fate is 8 months ago. Would you please try the bug, to see whether you can reproduce it?

**Comment by gabi2** [comment]
@izhu fate#316261 was SLES12 feature request and is tested for SLES 12 GM, bnc#936990 is also reported for SLES12.

**Comment by izhu** [comment]
@gabi2 Yes, but the bug exists, three of my team can reproduce it. Maybe the reason is kernel module  updated something. Anyway, it is here, can we try to reproduce it first?

**Comment by gabi2** [comment]
@izhu This means your test machine has SLES12 GM installed and all available updates?

**Comment by izhu** [comment]
It is easy to reproduce, use this version from github, create a target with "No Authentication" checked. Then try to log in it with yast-client, see what would happen

**Comment by izhu** [comment]
@gabi2 yes, SLES12 and latest updates

**Comment by gabi2** [comment]
I have tested on SLES12 with latest updates: Login to target is successful. see y2log:
2015-07-21 13:28:07 <5> e32(2636) [Ruby] modules/IscsiClientLib.rb:864 check connected status for ["10.160.64.216:3260", "iqn.2015-07.de.suse:72f6c0b4-baa3-48c3-a3f8-d62323aaf3eb", "default"] with IP check:true
2015-07-21 13:28:07 <1> e32(2636) [Ruby] modules/IscsiClientLib.rb:793 set node.session.auth.authmethod  for record ["10.160.64.216:3260", "iqn.2015-07.de.suse:72f6c0b4-baa3-48c3-a3f8-d62323aaf3eb", "default"]
2015-07-21 13:28:07 <1> e32(2636) [Ruby] modules/IscsiClientLib.rb:179 GetAdmCmd: LC_ALL=POSIX iscsiadm -m node -I default -T iqn.2015-07.de.suse:72f6c0b4-baa3-48c3-a3f8-d62323aaf3eb -p 10.160.64.216:3260 --op=update --name=node.session.auth.authmethod --value=None
2015-07-21 13:28:07 <1> e32(2636) [Ruby] modules/IscsiClientLib.rb:817 return value true
2015-07-21 13:28:07 <1> e32(2636) [Ruby] modules/IscsiClientLib.rb:179 GetAdmCmd: LC_ALL=POSIX iscsiadm -m node -I default -T iqn.2015-07.de.suse:72f6c0b4-baa3-48c3-a3f8-d62323aaf3eb -p 10.160.64.216:3260 --login
2015-07-21 13:28:07 <5> e32(2636) [Ruby] modules/IscsiClientLib.rb:1010 output $["exit":0, "stderr":"", "stdout":"Logging in to [iface: default, target: iqn.2015-07.de.suse:72f6c0b4-baa3-48c3-a3f8-d62323aaf3eb, portal: 10.160.64.216,3260] (multiple)\nLogin to [iface: default, target: iqn.2015-07.de.suse:72f6c0b4-baa3-48c3-a3f8-d62323aaf3eb, portal: 10.160.64.216,3260] successful.\n"]

**Comment by gabi2** [comment]
While login to a target where client name for access isn't specied failed:
2015-07-21 13:28:25 <1> e32(2636) [Ruby] modules/IscsiClientLib.rb:179 GetAdmCmd: LC_ALL=POSIX iscsiadm -m node -I default -T iqn.2015-07.de.suse:2afd322a-5dbf-413d-831a-a4e38e48250c -p 10.160.64.216:3260 --op=update --name=node.session.auth.authmethod --value=None
2015-07-21 13:28:25 <1> e32(2636) [Ruby] modules/IscsiClientLib.rb:817 return value true
2015-07-21 13:28:25 <1> e32(2636) [Ruby] modules/IscsiClientLib.rb:179 GetAdmCmd: LC_ALL=POSIX iscsiadm -m node -I default -T iqn.2015-07.de.suse:2afd322a-5dbf-413d-831a-a4e38e48250c -p 10.160.64.216:3260 --login
2015-07-21 13:28:25 <3> e32(2636) [bash] ShellCommand.cc(shellcommand):78 iscsiadm: Could not login to [iface: default, target: iqn.2015-07.de.suse:2afd322a-5dbf-413d-831a-a4e38e48250c, portal: 10.160.64.216,3260].
2015-07-21 13:28:25 <3> e32(2636) [bash] ShellCommand.cc(shellcommand):78 iscsiadm: initiator reported error (24 - iSCSI login failed due to authorization failure)
2015-07-21 13:28:25 <3> e32(2636) [bash] ShellCommand.cc(shellcommand):78 iscsiadm: Could not log into all portals
2015-07-21 13:28:25 <5> e32(2636) [Ruby] modules/IscsiClientLib.rb:1010 output $["exit":24, "stderr":"iscsiadm: Could not login to [iface: default, target: iqn.2015-07.de.suse:2afd322a-5dbf-413d-831a-a4e38e48250c, portal: 10.160.64.216,3260].\niscsiadm: initiator reported error (24 - iSCSI login failed due to authorization failure)\niscsiadm: Could not log into all portals\n", "stdout":"Logging in to [iface: default, target: iqn.2015-07.de.suse:2afd322a-5dbf-413d-831a-a4e38e48250c, portal: 10.160.64.216,3260] (multiple)\n"]

**Comment by gabi2** [comment]
As mentioned before: the requirement that any client has target access is covered by fate #318406.

**Comment by gabi2** [comment]
Probably 'demo mode' cannot be used at all because it only grants read-only access (AFAICS).

**Comment by izhu** [comment]
@gabi2 Yes, I also believe fate#318406 can make this work, but that is still under some discussions, more conversation with upstream also needed, we still not see the code for the fate done.
But the bug is here, the we need to fix the bug first, then if we can have the fate done, that would be nice.
Yes, "demo mode" only provide read-only access, but in the patch, I also disabled write protection, so it is not read-only anymore

**Comment by gabi2** [comment]
Which bug? Client access without authentication works like expected.

**Comment by gabi2** [comment]
Concerning demo mode: what I found is that demo mode should only be used for simple demo setups and should be only used in controlled environment ("Demo mode puts your data at risk!"), see http://linux-iscsi.org/wiki/ISCSI#Demo_mode.
fate#318406 is about investigation of best approach for required feature.

**Pull request closed without merging**
